export default {
  login: "CR7sewey",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars.githubusercontent.com/u/123294825?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/CR7sewey",
  html_url: "https://github.com/CR7sewey",
  followers_url: "https://api.github.com/users/CR7sewey/followers",
  following_url: "https://api.github.com/users/CR7sewey/following{/other_user}",
  gists_url: "https://api.github.com/users/CR7sewey/gists{/gist_id}",
  starred_url: "https://api.github.com/users/CR7sewey/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/CR7sewey/subscriptions",
  organizations_url: "https://api.github.com/users/CR7sewey/orgs",
  repos_url: "https://api.github.com/users/CR7sewey/repos",
  events_url: "https://api.github.com/users/CR7sewey/events{/privacy}",
  received_events_url: "https://api.github.com/users/CR7sewey/received_events",
  type: "User",
  site_admin: false,
  name: "Miguel",
  company: "Random Company",
  blog: "www.randomblog.com",
  location: "Lisbon",
  email: null,
  hireable: null,
  bio: "Just a normal guy",
  twitter_username: "none",
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",
};
